export const GET_TOON_INFO = 'GET_TOON_INFO';
export const INVALID_TOON = 'INVALID_TOON';
export const TOON_INFO_REQUESTED = 'TOON_INFO_REQUESTED';
export const TOON_INFO_FAILED = 'TOON_INFO_FAILED';
export const UPDATE_TOON_INFO = 'UPDATE_TOON_INFO';
export const SELECT_TOON = 'SELECT_TOON';


export const ASSIGN_USER_TOON_TO_PLATOON = 'ASSIGN_USER_TOON_TO_PLATOON';
export const REMOVE_USER_TOON_FROM_PLATOON = 'REMOVE_USER_TOON_FROM_PLATOON';


export const ADD_TOON_PLATTON = 'ADD_TOON_PLATTON';
export const REMOVE_TOON_PLATTON = 'REMOVE_TOON_PLATTON';



export const USER_REFRESH_REQUEST = 'USER_REFRESH_REQUEST';
export const USER_REFRESH = 'USER_REFRESH';
export const USER_REFRESH_FAILED ='USER_REFRESH_FAILED';
